#!/bin/bash
#_____________________________________________________________________________________________
# Seul root peut continuer, car seul root peut lire tous les fichiers de votre système !
#
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1
  fi
}
allow_only_root
#
cd /usr/share/ResPinGuy-File-Config/
. ./respinguy-config || exit 1
#
#######################################################################
# Vérification les dependences
bash /usr/share/ResPinGuy-File/respinguy-app-dep
#######################################################################
if [ ! $(dracut --list-modules | grep squash) ]; then
   echo "Impossible de trouver le module : squash"
   echo "Vous pouvez envisager d'installer le package contenant le module."
   echo "Généralement le package s'appel : dracut-squash"
	exit 1
fi
#_____________________________________________________________________________________________

echo "_ _ _"
echo "Résumer avant création"
echo "---"
echo "Nom : "$RPGBUILDNAME" - Emplacement Kernel : "$VMLINUZ" - Emplacement initramfs : "$INITRD
echo "Kernel Version : "$KERNEL" - Architecture : "$ARCH" Extension du squashfs : "$SQEX
echo "Dossier copier a partir de / : "$ROOTDIR
echo "Dossier de l'ISO final : "$RPGHOME" - Tout sera créer dans : /respinguy-build-dir/"
echo "_ _ _"
# echo "Nettoyage de /respinguy-build/ ..."
# rm -rf /respinguy-build-dir/

#
#_________________________________________________
#
cd /
echo "Préparation de /respinguy-build/ ..."
mkdir -p /respinguy-build-dir/LiveOS
echo "Terminé"
echo "_ _ _"
echo "Copie des fichiers de configuration ..."
echo "."
cp -r /usr/share/ResPinGuy-File/fichier/iso/isolinux/ /respinguy-build-dir/
echo "."
cp /usr/share/ResPinGuy-File-Config/bootimg.png /respinguy-build-dir/isolinux/
echo "."
cp /usr/share/ResPinGuy-File-Config/isolinux.cfg /respinguy-build-dir/isolinux/
echo "Terminé"
echo "_ _ _"
echo "Création de $RPGHOME ..."
rm -r $RPGHOME
mkdir $RPGHOME
echo "Terminé"
echo "_ _ _"
echo "Copie de $VMLINUZ ..."
cp $VMLINUZ /respinguy-build-dir/vmlinuz
##########################################################################################################################################################
echo "Terminé"
#
#_____________________________________________________________________________________________
# Création de l'image squashfs :
echo "Création du squashfs 0/1 ..."
SQSFDIR=""
for i in $ROOTDIR; do
   if [ -d /$i ]; then
      SQSFDIR="$SQSFDIR /$i"
   fi
done

mksquashfs $SQSFDIR /respinguy-build-dir/LiveOS/squashfs.img  \
 -noappend                 \
 -wildcards                \
 -e "proc/*"               \
 -e "proc/.*"              \
 -e "run/*"                \
 -e "run/.*"               \
 -e "tmp/*"                \
 -e "tmp/.*"               \
 -e "var/crash/*"          \
 -e "var/crash/.*"         \
 -e "swapfile"             \
 -e "root/.bash_history"   \
 -e "root/.cache"          \
 -e "root/.wget-hsts"      \
 -e "home/*/.bash_history" \
 -e "home/*/.cache"        \
 -e "home/*/.wget-hsts"

echo "Création du squashfs 1/1 ..."

echo "Création de l'initrd ..."
# ( PROBLEME A LA CREATION DE L'INITRD !!! )
#
dracut -N -a dmsquash-live /respinguy-build-dir/initrd --force

# dracut -a dmsquash-live --add-drivers overlay --add-drivers squashfs -i /usr/share/ResPinGuy-File-Config/fstab /etc/fstab -N -m "kernel-modules base" --filesystems "overlay squashfs" /respinguy-build-dir/initrd --force


#_____________________________________________________________________________________________
#Script Build
cd /
xorriso -as mkisofs -r -J -joliet-long -l -iso-level 3 -cache-inodes -isohybrid-mbr /usr/share/ResPinGuy-File/fichier/isohdpfx.bin -partition_offset 16 -A "$RPGBUILDNAME"  -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $RPGHOME/$RPGBUILDNAME-$ARCH.iso /respinguy-build-dir/

echo "_ _ _"
echo "Terminé. vous pourez votre résultat dans $RPGHOME"
echo "_ _ _"
#rm -rf /respinguy-build-dir/*
#_____________________________________________________________________________________________
