#!/bin/bash
#######################################################################
# Root
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer L'installation"; exit 1
  fi
}
allow_only_root
#######################################################################
clear
if [ ! $(type -p unzip) ]; then
	clear
   echo "Impossible de trouver la commande : unzip"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
read -p "Appuyez sur une touche pour lancer l'installation ..."
#######################################################################
# Téléchargement, deplacement, extraction, ...
wget http://respinguy.tk/ftp/file-respinguy/file-respinguy.zip
clear
read -p "Continuer ..."
mv file-respinguy.zip /tmp/
echo "... [1/5]"
cd /tmp/
echo "... [2/5]"
unzip file-respinguy.zip
echo "... [3/5]"
rm file-respinguy.zip
echo "... [4/5]"
cd /tmp/file-respinguy/
echo "... [5/5]"
#######################################################################
# Copie, ...
read -p "Continuer ..."
cp respinguy /usr/bin/
chmod +x /usr/bin/respinguy
echo "... [1/5]"
cp respinguy-app-rm /usr/bin/
chmod +x /usr/bin/respinguy-app-rm
echo "... [2/5]"
cp respinguy-app-up /usr/bin/
chmod +x /usr/bin/respinguy-app-up
echo "... [3/5]"
cp respinguy-build /usr/bin/
chmod +x /usr/bin/respinguy-build
echo "... [4/5]"
cp respinguy-config /usr/bin/
chmod +x /usr/bin/respinguy-config
echo "... [5/5]"
echo "Les commandes sont Installer."
#
cp -r ResPinGuy-File-Conf/ /usr/share/
echo "... [1/4]"
cp -r ResPinGuy-File/ /usr/share/
echo "... [2/4]"
cp -r respinguy-build-dir /
echo "... [3/4]"
rm -r /tmp/file-respinguy/
echo "... [4/4]"
echo "Les Fichiers sont Installer."
#
if [ ! $(type -p mkinitramfs) ]; then
	clear
  echo "mkinitramfs n'est pas installer !"
  echo "installation de mkinitramfs"
  read -p "Continuer ..."
  cd /tmp/
  echo "... [1/7]"
  wget http://respinguy.tk/ftp/file-respinguy/mkinitramfs-respinguy.zip
  echo "... [2/7]"
  unzip mkinitramfs-respinguy.zip
  echo "... [3/7]"
  rm mkinitramfs-respinguy.zip
  echo "... [4/7]"
  chmod -R +x /tmp/mkinitramfs-respinguy/*
  echo "... [5/7]"
  cd /tmp/mkinitramfs-respinguy/mkinitramfs/
  echo "... [6/7]"
  bash /tmp/mkinitramfs-respinguy/mkinitramfs/install
  echo "... [7/7]"
  read -p "Continuer ..."
  clear
  if [ ! $(type -p bsdcpio) ]; then
    clear
    echo "libarchive n'est pas installer !"
    echo "installation de compilation de libarchive"
    read -p "Continuer ..."
    cd /tmp/mkinitramfs-respinguy/libarchive/
    echo "... [1/2]"
    bash /tmp/mkinitramfs-respinguy/libarchive/install
    echo "... [2/2]"
    read -p "Continuer ..."
    clear
	fi
  rm -r /tmp/mkinitramfs-respinguy/
fi
#################################
read -p "ResPinGuy est executable sur votre machine. Terminer."
clear
echo "---"
echo "Lancer la commande : respinguy"
echo "---"
#######################################################################