#!/bin/bash
#######################################################################
# Root
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer Suppression"; exit 1
  fi
}
allow_only_root
#######################################################################
clear
read -p "Appuyez sur une touche pour lancer la Suppression ..."
#######################################################################
# Suppression, ...
rm /usr/bin/respinguy
echo "... [1/5]"
rm /usr/bin/respinguy-app-rm
echo "... [2/5]"
rm /usr/bin/respinguy-app-up
echo "... [3/5]"
rm /usr/bin/respinguy-build
echo "... [4/5]"
rm /usr/bin/respinguy-config
echo "... [5/5]"
echo "Les commandes sont Supprimer."
#
rm -r /usr/share/ResPinGuy-File/
echo "... [1/3]"
rm -r /usr/share/ResPinGuy-File-Conf/
echo "... [2/3]"
rm -r /respinguy-build-dir/
echo "... [3/3]"
echo "Les Fichiers sont Installer."
clear
#######################################################################
echo "ResPinGuy n'est plus sur votre machine."
read -p "Terminer."
clear
#######################################################################