#!/bin/bash
#######################################################################
rm Ver-Dep-ResPinGuy
#_________________________________________________
# Vérifier l'outils sudo
if [ ! $(type -p sudo) ]; then
	clear
   echo "Impossible de trouver la commande : sudo"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier l'outils wget
if [ ! $(type -p wget) ]; then
	clear
   echo "Impossible de trouver la commande : wget"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier l'outils unzip
if [ ! $(type -p unzip) ]; then
	clear
   echo "Impossible de trouver la commande : ..."
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier l'outils bash
if [ ! $(type -p bash) ]; then
	clear
   echo "Impossible de trouver la commande : bash"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier l'outils de uname
if [ ! $(type -p uname) ]; then
	clear
   echo "Impossible de trouver la commande : uname"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier l'outils nano
if [ ! $(type -p nano) ]; then
	clear
   echo "Impossible de trouver la commande : nano"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier les mksquashfs avec compression xz
if [ "$(mksquashfs 2>&1 | grep "Xdict-size")" = "" ]; then
   clear
   echo "Impossible de trouver la commande  : mksquashfs | Ou ne prend pas en charge -comp xz."
   echo "Vous pouvez envisager d'installer le package contenant la commande."
   exit 1
fi
#_________________________________________________
# Vérifier l'outils de création de l'image ISO
if [ ! $(type -p xorriso) ]; then
	clear
   echo "Impossible de trouver la commande : xorriso"
   echo "Vous pouvez envisager d'installer le package contenant la commande."
	exit 1
fi
#_________________________________________________
# Vérifier l'outils de création de initrd
#if [ ! $(type -p mkinitramfs) ]; then
#	clear
#   echo "Impossible de trouver la commande : mkinitramfs"
#   echo "Vous pouvez envisager d'installer le package contenant la commande."
#	exit 1
#fi
#######################################################################
echo "Tous les dépendances sont bien installer sur votre système"
exit
#_________________________________________________
# Vérifier l'outils de ...
#if [ ! $(type -p ...) ]; then
#	clear
#   echo "Impossible de trouver la commande : ..."
#   echo "Vous pouvez envisager d'installer le package contenant la commande."
#	exit 1
#fi