#!/bin/bash
#_____________________________________________________________________________________________
# Seul root peut continuer, car seul root peut lire tous les fichiers de votre système !
allow_only_root()
{
  if [ "0$UID" -ne 0 ]; then
     echo "Merci d'être en root pour lancer : $(basename $0)"; exit 1
  fi
}
allow_only_root
#_____________________________________________________________________________________________
nano /usr/share/ResPinGuy-File-Conf/respinguy-config
cd /usr/share/ResPinGuy-File-Conf/
clear
ls /usr/share/ResPinGuy-File-Conf/
echo "Voici tout les fichiers modifiables | le dossier original-save/ est une savegarde de la configuration original"